name: re_widgets
description: A Very Good Project created by Very Good CLI.
version: 0.2.1+7
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  flutter:
    sdk: flutter
  re_seedwork:
    git:
      url: https://github.com/radomir9720/re_seedwork.git
      ref: "0.3.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
