name: widgetbook_app
description: Widgetbook app for re_widgets package.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dart
  re_widgets:
    path: ../
  re_seedwork:
    git:
      url: https://github.com/radomir9720/re_seedwork.git
      ref: "0.2.0"
  cupertino_icons: ^1.0.2
  widgetbook_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # lints
  flutter_lints: ^2.0.0

  # widgetbook
  widgetbook: ^2.4.1
  build_runner: ^2.3.3
  widgetbook_generator: ^2.4.1

flutter:
  uses-material-design: true
