name: widgetbook_app
description: Widgetbook app for re_widgets package.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dart
  re_widgets:
    path: ../
  cupertino_icons: ^1.0.2
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # lints
  flutter_lints: ^2.0.0

  # widgetbook
  widgetbook: ^3.3.0
  build_runner: ^2.4.6
  widgetbook_generator: ^3.2.0

flutter:
  uses-material-design: true
